### ISSUE TITLE
Temperature example has gaps

### ISSUE THREAD

**Issue by artgoldberg** [ricardoduarte/python-for-developers#14]
Hello Ricardo

Great tutorial, at least in the first few chapters that I've read. I'm adapting your materials for a course at the Mount Sinai School of Medicine. 

This example in Chap. 3 has gaps, which I've fixed:

    temp_C = 23 # temperature value used to test

    if temp_C <= 0:
        print('Freezing...')
    elif 0 < temp_C <= 20:
        print('Cold')
    elif 20 < temp_C <= 25:
        print('Normal')
    elif 25 < temp_C <= 35:
        print('Hot')
    else:
        print('Very Hot!')

**Comment by ricardoduarte** [comment]
Hi,
Thank you so much for using the material. Actually, I'm not the book's author, it is a work colleague, I just converted the material into Jupyter notebooks.

Thank you again for fixing the gaps.
