### ISSUE TITLE
Recusive addition of list is not working properly

### ISSUE THREAD

**Issue by mrtushartiwari** [ricardoduarte/python-for-developers#15]
Chapter 9: Scope of names 
I am using python3
for the addlist(list) function.
`unsupported operand type(s) for +=: 'int' and 'list'`

**Comment by ricardoduarte** [comment]
Thank you for opening this issue. Actually, all of the examples included in this book version works only with Python 2.x (it is an old book).

There is a Python 3.x version of this book but it is only a printed version and it was written in Brazilian Portuguese.

When the editor rights expire, maybe we'll publish this book online.
